package com.mapper;

import com.entity.SellerInfo;
import com.entity.SellerInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SellerInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seller_info
     *
     * @mbggenerated Sat Apr 20 14:27:59 CST 2019
     */
    int countByExample(SellerInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seller_info
     *
     * @mbggenerated Sat Apr 20 14:27:59 CST 2019
     */
    int deleteByExample(SellerInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seller_info
     *
     * @mbggenerated Sat Apr 20 14:27:59 CST 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seller_info
     *
     * @mbggenerated Sat Apr 20 14:27:59 CST 2019
     */
    int insert(SellerInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seller_info
     *
     * @mbggenerated Sat Apr 20 14:27:59 CST 2019
     */
    int insertSelective(SellerInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seller_info
     *
     * @mbggenerated Sat Apr 20 14:27:59 CST 2019
     */
    List<SellerInfo> selectByExample(SellerInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seller_info
     *
     * @mbggenerated Sat Apr 20 14:27:59 CST 2019
     */
    SellerInfo selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seller_info
     *
     * @mbggenerated Sat Apr 20 14:27:59 CST 2019
     */
    int updateByExampleSelective(@Param("record") SellerInfo record, @Param("example") SellerInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seller_info
     *
     * @mbggenerated Sat Apr 20 14:27:59 CST 2019
     */
    int updateByExample(@Param("record") SellerInfo record, @Param("example") SellerInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seller_info
     *
     * @mbggenerated Sat Apr 20 14:27:59 CST 2019
     */
    int updateByPrimaryKeySelective(SellerInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seller_info
     *
     * @mbggenerated Sat Apr 20 14:27:59 CST 2019
     */
    int updateByPrimaryKey(SellerInfo record);
}