package com.entity;

import java.math.BigDecimal;
import java.util.Date;

public class OrderMaster {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_master.order_id
     *
     * @mbggenerated Sat Apr 20 14:27:59 CST 2019
     */
    private String orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_master.buyer_name
     *
     * @mbggenerated Sat Apr 20 14:27:59 CST 2019
     */
    private String buyerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_master.buyer_phone
     *
     * @mbggenerated Sat Apr 20 14:27:59 CST 2019
     */
    private String buyerPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_master.buyer_addrss
     *
     * @mbggenerated Sat Apr 20 14:27:59 CST 2019
     */
    private String buyerAddrss;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_master.buyer_openid
     *
     * @mbggenerated Sat Apr 20 14:27:59 CST 2019
     */
    private String buyerOpenid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_master.order_amount
     *
     * @mbggenerated Sat Apr 20 14:27:59 CST 2019
     */
    private BigDecimal orderAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_master.order_status
     *
     * @mbggenerated Sat Apr 20 14:27:59 CST 2019
     */
    private Byte orderStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_master.pay_status
     *
     * @mbggenerated Sat Apr 20 14:27:59 CST 2019
     */
    private Byte payStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_master.create_time
     *
     * @mbggenerated Sat Apr 20 14:27:59 CST 2019
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_master.update_time
     *
     * @mbggenerated Sat Apr 20 14:27:59 CST 2019
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_master.order_id
     *
     * @return the value of order_master.order_id
     *
     * @mbggenerated Sat Apr 20 14:27:59 CST 2019
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_master.order_id
     *
     * @param orderId the value for order_master.order_id
     *
     * @mbggenerated Sat Apr 20 14:27:59 CST 2019
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_master.buyer_name
     *
     * @return the value of order_master.buyer_name
     *
     * @mbggenerated Sat Apr 20 14:27:59 CST 2019
     */
    public String getBuyerName() {
        return buyerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_master.buyer_name
     *
     * @param buyerName the value for order_master.buyer_name
     *
     * @mbggenerated Sat Apr 20 14:27:59 CST 2019
     */
    public void setBuyerName(String buyerName) {
        this.buyerName = buyerName == null ? null : buyerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_master.buyer_phone
     *
     * @return the value of order_master.buyer_phone
     *
     * @mbggenerated Sat Apr 20 14:27:59 CST 2019
     */
    public String getBuyerPhone() {
        return buyerPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_master.buyer_phone
     *
     * @param buyerPhone the value for order_master.buyer_phone
     *
     * @mbggenerated Sat Apr 20 14:27:59 CST 2019
     */
    public void setBuyerPhone(String buyerPhone) {
        this.buyerPhone = buyerPhone == null ? null : buyerPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_master.buyer_addrss
     *
     * @return the value of order_master.buyer_addrss
     *
     * @mbggenerated Sat Apr 20 14:27:59 CST 2019
     */
    public String getBuyerAddrss() {
        return buyerAddrss;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_master.buyer_addrss
     *
     * @param buyerAddrss the value for order_master.buyer_addrss
     *
     * @mbggenerated Sat Apr 20 14:27:59 CST 2019
     */
    public void setBuyerAddrss(String buyerAddrss) {
        this.buyerAddrss = buyerAddrss == null ? null : buyerAddrss.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_master.buyer_openid
     *
     * @return the value of order_master.buyer_openid
     *
     * @mbggenerated Sat Apr 20 14:27:59 CST 2019
     */
    public String getBuyerOpenid() {
        return buyerOpenid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_master.buyer_openid
     *
     * @param buyerOpenid the value for order_master.buyer_openid
     *
     * @mbggenerated Sat Apr 20 14:27:59 CST 2019
     */
    public void setBuyerOpenid(String buyerOpenid) {
        this.buyerOpenid = buyerOpenid == null ? null : buyerOpenid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_master.order_amount
     *
     * @return the value of order_master.order_amount
     *
     * @mbggenerated Sat Apr 20 14:27:59 CST 2019
     */
    public BigDecimal getOrderAmount() {
        return orderAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_master.order_amount
     *
     * @param orderAmount the value for order_master.order_amount
     *
     * @mbggenerated Sat Apr 20 14:27:59 CST 2019
     */
    public void setOrderAmount(BigDecimal orderAmount) {
        this.orderAmount = orderAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_master.order_status
     *
     * @return the value of order_master.order_status
     *
     * @mbggenerated Sat Apr 20 14:27:59 CST 2019
     */
    public Byte getOrderStatus() {
        return orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_master.order_status
     *
     * @param orderStatus the value for order_master.order_status
     *
     * @mbggenerated Sat Apr 20 14:27:59 CST 2019
     */
    public void setOrderStatus(Byte orderStatus) {
        this.orderStatus = orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_master.pay_status
     *
     * @return the value of order_master.pay_status
     *
     * @mbggenerated Sat Apr 20 14:27:59 CST 2019
     */
    public Byte getPayStatus() {
        return payStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_master.pay_status
     *
     * @param payStatus the value for order_master.pay_status
     *
     * @mbggenerated Sat Apr 20 14:27:59 CST 2019
     */
    public void setPayStatus(Byte payStatus) {
        this.payStatus = payStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_master.create_time
     *
     * @return the value of order_master.create_time
     *
     * @mbggenerated Sat Apr 20 14:27:59 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_master.create_time
     *
     * @param createTime the value for order_master.create_time
     *
     * @mbggenerated Sat Apr 20 14:27:59 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_master.update_time
     *
     * @return the value of order_master.update_time
     *
     * @mbggenerated Sat Apr 20 14:27:59 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_master.update_time
     *
     * @param updateTime the value for order_master.update_time
     *
     * @mbggenerated Sat Apr 20 14:27:59 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}