package com.entity;

import java.math.BigDecimal;
import java.util.Date;

public class ProductInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.product_id
     *
     * @mbggenerated Sat Apr 20 14:27:59 CST 2019
     */
    private String productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.product_name
     *
     * @mbggenerated Sat Apr 20 14:27:59 CST 2019
     */
    private String productName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.product_price
     *
     * @mbggenerated Sat Apr 20 14:27:59 CST 2019
     */
    private BigDecimal productPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.product_age
     *
     * @mbggenerated Sat Apr 20 14:27:59 CST 2019
     */
    private Integer productAge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.product_size
     *
     * @mbggenerated Sat Apr 20 14:27:59 CST 2019
     */
    private String productSize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.product_type
     *
     * @mbggenerated Sat Apr 20 14:27:59 CST 2019
     */
    private String productType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.product_stock
     *
     * @mbggenerated Sat Apr 20 14:27:59 CST 2019
     */
    private Integer productStock;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.product_proname
     *
     * @mbggenerated Sat Apr 20 14:27:59 CST 2019
     */
    private String productProname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.product_description
     *
     * @mbggenerated Sat Apr 20 14:27:59 CST 2019
     */
    private String productDescription;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.product_icon
     *
     * @mbggenerated Sat Apr 20 14:27:59 CST 2019
     */
    private String productIcon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.product_status
     *
     * @mbggenerated Sat Apr 20 14:27:59 CST 2019
     */
    private Byte productStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.category_type
     *
     * @mbggenerated Sat Apr 20 14:27:59 CST 2019
     */
    private Integer categoryType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.create_time
     *
     * @mbggenerated Sat Apr 20 14:27:59 CST 2019
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.update_time
     *
     * @mbggenerated Sat Apr 20 14:27:59 CST 2019
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.product_id
     *
     * @return the value of product_info.product_id
     *
     * @mbggenerated Sat Apr 20 14:27:59 CST 2019
     */
    public String getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.product_id
     *
     * @param productId the value for product_info.product_id
     *
     * @mbggenerated Sat Apr 20 14:27:59 CST 2019
     */
    public void setProductId(String productId) {
        this.productId = productId == null ? null : productId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.product_name
     *
     * @return the value of product_info.product_name
     *
     * @mbggenerated Sat Apr 20 14:27:59 CST 2019
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.product_name
     *
     * @param productName the value for product_info.product_name
     *
     * @mbggenerated Sat Apr 20 14:27:59 CST 2019
     */
    public void setProductName(String productName) {
        this.productName = productName == null ? null : productName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.product_price
     *
     * @return the value of product_info.product_price
     *
     * @mbggenerated Sat Apr 20 14:27:59 CST 2019
     */
    public BigDecimal getProductPrice() {
        return productPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.product_price
     *
     * @param productPrice the value for product_info.product_price
     *
     * @mbggenerated Sat Apr 20 14:27:59 CST 2019
     */
    public void setProductPrice(BigDecimal productPrice) {
        this.productPrice = productPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.product_age
     *
     * @return the value of product_info.product_age
     *
     * @mbggenerated Sat Apr 20 14:27:59 CST 2019
     */
    public Integer getProductAge() {
        return productAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.product_age
     *
     * @param productAge the value for product_info.product_age
     *
     * @mbggenerated Sat Apr 20 14:27:59 CST 2019
     */
    public void setProductAge(Integer productAge) {
        this.productAge = productAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.product_size
     *
     * @return the value of product_info.product_size
     *
     * @mbggenerated Sat Apr 20 14:27:59 CST 2019
     */
    public String getProductSize() {
        return productSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.product_size
     *
     * @param productSize the value for product_info.product_size
     *
     * @mbggenerated Sat Apr 20 14:27:59 CST 2019
     */
    public void setProductSize(String productSize) {
        this.productSize = productSize == null ? null : productSize.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.product_type
     *
     * @return the value of product_info.product_type
     *
     * @mbggenerated Sat Apr 20 14:27:59 CST 2019
     */
    public String getProductType() {
        return productType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.product_type
     *
     * @param productType the value for product_info.product_type
     *
     * @mbggenerated Sat Apr 20 14:27:59 CST 2019
     */
    public void setProductType(String productType) {
        this.productType = productType == null ? null : productType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.product_stock
     *
     * @return the value of product_info.product_stock
     *
     * @mbggenerated Sat Apr 20 14:27:59 CST 2019
     */
    public Integer getProductStock() {
        return productStock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.product_stock
     *
     * @param productStock the value for product_info.product_stock
     *
     * @mbggenerated Sat Apr 20 14:27:59 CST 2019
     */
    public void setProductStock(Integer productStock) {
        this.productStock = productStock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.product_proname
     *
     * @return the value of product_info.product_proname
     *
     * @mbggenerated Sat Apr 20 14:27:59 CST 2019
     */
    public String getProductProname() {
        return productProname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.product_proname
     *
     * @param productProname the value for product_info.product_proname
     *
     * @mbggenerated Sat Apr 20 14:27:59 CST 2019
     */
    public void setProductProname(String productProname) {
        this.productProname = productProname == null ? null : productProname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.product_description
     *
     * @return the value of product_info.product_description
     *
     * @mbggenerated Sat Apr 20 14:27:59 CST 2019
     */
    public String getProductDescription() {
        return productDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.product_description
     *
     * @param productDescription the value for product_info.product_description
     *
     * @mbggenerated Sat Apr 20 14:27:59 CST 2019
     */
    public void setProductDescription(String productDescription) {
        this.productDescription = productDescription == null ? null : productDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.product_icon
     *
     * @return the value of product_info.product_icon
     *
     * @mbggenerated Sat Apr 20 14:27:59 CST 2019
     */
    public String getProductIcon() {
        return productIcon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.product_icon
     *
     * @param productIcon the value for product_info.product_icon
     *
     * @mbggenerated Sat Apr 20 14:27:59 CST 2019
     */
    public void setProductIcon(String productIcon) {
        this.productIcon = productIcon == null ? null : productIcon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.product_status
     *
     * @return the value of product_info.product_status
     *
     * @mbggenerated Sat Apr 20 14:27:59 CST 2019
     */
    public Byte getProductStatus() {
        return productStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.product_status
     *
     * @param productStatus the value for product_info.product_status
     *
     * @mbggenerated Sat Apr 20 14:27:59 CST 2019
     */
    public void setProductStatus(Byte productStatus) {
        this.productStatus = productStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.category_type
     *
     * @return the value of product_info.category_type
     *
     * @mbggenerated Sat Apr 20 14:27:59 CST 2019
     */
    public Integer getCategoryType() {
        return categoryType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.category_type
     *
     * @param categoryType the value for product_info.category_type
     *
     * @mbggenerated Sat Apr 20 14:27:59 CST 2019
     */
    public void setCategoryType(Integer categoryType) {
        this.categoryType = categoryType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.create_time
     *
     * @return the value of product_info.create_time
     *
     * @mbggenerated Sat Apr 20 14:27:59 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.create_time
     *
     * @param createTime the value for product_info.create_time
     *
     * @mbggenerated Sat Apr 20 14:27:59 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.update_time
     *
     * @return the value of product_info.update_time
     *
     * @mbggenerated Sat Apr 20 14:27:59 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.update_time
     *
     * @param updateTime the value for product_info.update_time
     *
     * @mbggenerated Sat Apr 20 14:27:59 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}